# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

count_rows_c <- function(list_df) {
    .Call('_pearls_count_rows_c', PACKAGE = 'pearls', list_df)
}

count_columns_c <- function(list_df) {
    .Call('_pearls_count_columns_c', PACKAGE = 'pearls', list_df)
}

